MyMatrimony/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyMatrimony.Models;

namespace MyMatrimony.Controllers
{
    public class MembersController : Controller
    {
        private MyMatrimonyDBEntities db = new MyMatrimonyDBEntities();

        // GET: Members
        public ActionResult ListMembers()
        {
            #region Filters - City Model
            List<CheckBoxModel> cityModel = new List<CheckBoxModel>();
            foreach (var city in db.tblCityMasters.ToList())
            {
                cityModel.Add(new CheckBoxModel() { Text = city.CityName, Value = city.Id.ToString(), isChecked = true });
            }
            ViewBag.Cities = cityModel;
            #endregion
            
            #region Filters - Religion Model
            List<CheckBoxModel> religionModel = new List<CheckBoxModel>();
            foreach (var religion in db.tblReligionMasters.ToList())
            {
                religionModel.Add(new CheckBoxModel() { Text = religion.ReligionName, Value = religion.Id.ToString(), isChecked = true });
            }
            ViewBag.Religions = religionModel;

            var tblMembers = db.tblMembers.Include(t => t.tblCasteMaster).Include(t => t.tblCityMaster).Include(t => t.tblGenderMaster).Include(t => t.tblHeightMaster).Include(t => t.tblMotherTongueMaster).Include(t => t.tblReligionMaster).Include(t => t.tblSkinToneMaster).Include(t => t.tblAnnualIncomeMaster).Include(t => t.tblBodyTypeMaster).Include(t => t.tblDietMaster);
            return View(tblMembers.ToList()); 
            #endregion
        }

        /// <summary>
        /// Apply filters if any and send the filtered data back
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ListMembers(FormCollection form)
        {
            
            #region City Model
            // Get the city checkbox values
            var selectedCityChkBxIds = form.AllKeys.Where(x => x.StartsWith("chkCity_") && (form[x].Contains("true"))).ToList();
            List<string> selectedCityIds = new List<string>();
            foreach (var cityId in selectedCityChkBxIds)
            {
                selectedCityIds.Add(cityId.Substring(cityId.IndexOf('_') + 1));
            }

            // Form the cities master data to show in city filter
            List<CheckBoxModel> cityModel = new List<CheckBoxModel>();
            foreach (var city in db.tblCityMasters.ToList())
            {
                cityModel.Add(new CheckBoxModel() { Text = city.CityName, Value = city.Id.ToString(), isChecked = selectedCityIds.Contains(city.Id.ToString()) });
            }
            ViewBag.Cities = cityModel;
            #endregion

            #region Religion Model
            // Get the religion checkbox values
            var selectedReligionChkBxIds = form.AllKeys.Where(x => x.StartsWith("chkReligion_") && (form[x].Contains("true"))).ToList();
            List<string> selectedReligionIds = new List<string>();
            foreach (var religionId in selectedReligionChkBxIds)
            {
                selectedReligionIds.Add(religionId.Substring(religionId.IndexOf('_') + 1));
            }

            // Form the religion master data to show in religion filter
            List<CheckBoxModel> religionModel = new List<CheckBoxModel>();
            foreach (var religion in db.tblReligionMasters.ToList())
            {
                religionModel.Add(new CheckBoxModel() { Text = religion.ReligionName, Value = religion.Id.ToString(), isChecked = selectedReligionIds.Contains(religion.Id.ToString()) });
            }
            ViewBag.Religions = religionModel;
            #endregion

            var tblMembers = db.tblMembers.Include(t => t.tblCasteMaster).Include(t => t.tblCityMaster).Include(t => t.tblGenderMaster).Include(t => t.tblHeightMaster).Include(t => t.tblMotherTongueMaster).Include(t => t.tblReligionMaster).Include(t => t.tblSkinToneMaster).Include(t => t.tblAnnualIncomeMaster).Include(t => t.tblBodyTypeMaster).Include(t => t.tblDietMaster);

            // Apply filters
            tblMembers = tblMembers.Where(x => selectedCityIds.Contains(x.CityId.ToString()) && selectedReligionIds.Contains(x.ReligionId.ToString()));
            
            return View(tblMembers.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMember tblMember = db.tblMembers.Find(id);
            if (tblMember == null)
            {
                return HttpNotFound();
            }
            return View(tblMember);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            ViewBag.CasteId = new SelectList(db.tblCasteMasters, "Id", "CasteName");
            ViewBag.CityId = new SelectList(db.tblCityMasters, "Id", "CityName");
            ViewBag.GenderId = db.tblGenderMasters.ToList();
            ViewBag.HeightId = new SelectList(db.tblHeightMasters, "Id", "Height");
            ViewBag.MotherTongueId = new SelectList(db.tblMotherTongueMasters, "Id", "MotherTongue");
            ViewBag.ReligionId = new SelectList(db.tblReligionMasters, "Id", "ReligionName");
            ViewBag.SkinToneId = new SelectList(db.tblSkinToneMasters, "Id", "SkinTone");
            ViewBag.AnnualIncomeId = new SelectList(db.tblAnnualIncomeMasters, "Id", "AnnualIncome");
            ViewBag.BodyTypeId = new SelectList(db.tblBodyTypeMasters, "Id", "BodyType");
            ViewBag.DietId = new SelectList(db.tblDietMasters, "Id", "Diet");
            ViewBag.ZodiacSignId = new SelectList(db.tblZodiacSigns, "Id", "ZodiacSign");
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "", Include = "Id,Email,Password,ConfirmPassword,Name,DateOfBirth,MobileNo,CityId,ReligionId,HeightId,MotherTongueId,CasteId,GenderId,SkinToneId,BodyTypeId,BodyWeight,DietId,Drink,Smoke,Education,AnnualIncomeId,Occupation,ZodiacSignId,Hobbies,AboutMyself")] tblMember tblMember)
        {
            if (ModelState.IsValid)
            {
                db.tblMembers.Add(tblMember);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CasteId = new SelectList(db.tblCasteMasters, "Id", "CasteName", tblMember.CasteId);
            ViewBag.CityId = new SelectList(db.tblCityMasters, "Id", "CityName", tblMember.CityId);
            ViewBag.GenderId = db.tblGenderMasters.ToList();
            ViewBag.HeightId = new SelectList(db.tblHeightMasters, "Id", "Height", tblMember.HeightId);
            ViewBag.MotherTongueId = new SelectList(db.tblMotherTongueMasters, "Id", "MotherTongue", tblMember.MotherTongueId);
            ViewBag.ReligionId = new SelectList(db.tblReligionMasters, "Id", "ReligionName", tblMember.ReligionId);
            ViewBag.SkinToneId = new SelectList(db.tblSkinToneMasters, "Id", "SkinTone", tblMember.SkinToneId);
            ViewBag.AnnualIncomeId = new SelectList(db.tblAnnualIncomeMasters, "Id", "AnnualIncome", tblMember.AnnualIncomeId);
            ViewBag.BodyTypeId = new SelectList(db.tblBodyTypeMasters, "Id", "BodyType", tblMember.BodyTypeId);
            ViewBag.DietId = new SelectList(db.tblDietMasters, "Id", "Diet", tblMember.DietId);
            ViewBag.ZodiacSignId = new SelectList(db.tblZodiacSigns, "Id", "ZodiacSign");
            return View(tblMember);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblMember tblMember = db.tblMembers.Find(id);
            if (tblMember == null)
            {
                return HttpNotFound();
            }
            ViewBag.CasteId = new SelectList(db.tblCasteMasters, "Id", "CasteName", tblMember.CasteId);
            ViewBag.CityId = new SelectList(db.tblCityMasters, "Id", "CityName", tblMember.CityId);
            ViewBag.GenderId = new SelectList(db.tblGenderMasters, "Id", "Gender", tblMember.GenderId);
            ViewBag.HeightId = new SelectList(db.tblHeightMasters, "Id", "Height", tblMember.HeightId);
            ViewBag.MotherTongueId = new SelectList(db.tblMotherTongueMasters, "Id", "MotherTongue", tblMember.MotherTongueId);
            ViewBag.ReligionId = new SelectList(db.tblReligionMasters, "Id", "ReligionName", tblMember.ReligionId);
            ViewBag.SkinToneId = new SelectList(db.tblSkinToneMasters, "Id", "SkinTone", tblMember.SkinToneId);
            ViewBag.AnnualIncomeId = new SelectList(db.tblAnnualIncomeMasters, "Id", "AnnualIncome", tblMember.AnnualIncomeId);
            ViewBag.BodyTypeId = new SelectList(db.tblBodyTypeMasters, "Id", "BodyType", tblMember.BodyTypeId);
            ViewBag.DietId = new SelectList(db.tblDietMasters, "Id", "Diet", tblMember.DietId);
            return View(tblMember);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

MyMatrimony/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - MyMatrimony</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="~/Scripts/bootstrap-toolkit.js"></script>

    <script src="~/Scripts/myScript.js"></script>

    @Styles.Render("~/Content/css")
    @* @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</head>
<body style="margin-top:20px">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light navbar-light bg-light">
        <div class="container-fluid">

            <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="color:tomato">
                <i class="fas fa-heart"></i><span style="font-family:Segoe Print; color:tomato; font-weight:bold">MyMatrimony</span>
                @*@Html.ActionLink("MyMatrimony", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", style = "font-family:Segoe Print; color:tomato; font-weight:1000" })*@
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("About", "Home")">About</a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Contact", "Contact", "Home", new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown d-lg-none d-xl-block">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("ListMembers", "Members")">All Members</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item d-lg-none d-xl-block">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0 mr-4">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Register", "Create", "Members", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Log in</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    <!-- Modal - Login -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog" role="dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">
                        Login
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm())
                    {
                        <dl class="dl-horizontal">
                            <dt>
                                User Name
                            </dt>
                            <dd>
                                @Html.TextBox("UserName", null, new { @class = "form-control" })
                            </dd>
                            <dt>
                                Password
                            </dt>
                            <dd>
                                @Html.Password("Password", null, new { @class = "form-control" })
                            </dd>
                        </dl>
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="alert('Contact details sent to you throgh SMS.');">Login</button>
                </div>
            </div>
        </div>
    </div>



</body>
</html>